export const GET_POSTS_REQUESTED = 'GET_POSTS_REQUESTED';
export const GET_POSTS_SUCCESS = 'GET_POSTS_SUCCESS';
export const GET_POSTS_FAILED = 'GET_POSTS_FAILED';

export const GET_IMAGE_REQUESTED = 'GET_IMAGE_REQUESTED';
export const GET_IMAGE_SUCCESS = 'GET_IMAGE_SUCCESS';
export const GET_IMAGE_FAILED = 'GET_IMAGE_FAILED';